# WordPress, phpmyadmin et MariaDB
# Il faut utiliser les variables d'environnement
# Pour l'accès à la BD et la configuration de WordPress
# WordPress et phpmyadmin dépendent de la base de données MariaDB
# Le réseau reseauWP est utilisé pour isoler les services WordPress, phpmyadmin et MariaDB

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - reseauWP

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WP_USER}
      WORDPRESS_DB_PASSWORD: ${WP_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    ports:
      - "${WORDPRESS_PORT}:80"
    networks:
      - reseauWP

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - reseauWP

volumes:
  mariadb_data:
  wordpress_data: